force-app/main/default/objects/Expertise__c/Expertise__c.object-meta.xml
<CustomObject>
    <label>Expertise</label>
    <nameField>
        <label>Expertise</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expertise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expertise__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Certified required or not</description>
    <inlineHelpText>Certification required for this expertise?</inlineHelpText>
    <label>Certification Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expertise__c/fields/Hot_Technology__c.field-meta.xml
<CustomField>
    <fullName>Hot_Technology__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hot Technology</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expertise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <inlineHelpText>Type</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-technical</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <description>Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category</description>
    <inlineHelpText>Category</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analytics and Discovery</fullName>
            </value>
            <value>
                <fullName>Business transformation</fullName>
            </value>
            <value>
                <fullName>Custom analytics build</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>Sales Cloud Einstein analytics</fullName>
            </value>
            <value>
                <fullName>Salesforce customisation</fullName>
            </value>
            <value>
                <fullName>Salesforce implementation</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projects__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projects_and_Expertise__c/Projects_and_Expertise__c.object-meta.xml
<CustomObject>
    <description>Projects and Expertise</description>
    <label>Projects and Expertise</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Projects and Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects and Expertises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects_and_Expertise__c/fields/Expertise_Level__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Level__c</fullName>
    <description>Expertise Level</description>
    <inlineHelpText>Expertise Level</inlineHelpText>
    <label>Expertise Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Projects_and_Resources__c/Projects_and_Resources__c.object-meta.xml
<CustomObject>
    <description>Projects and Resources</description>
    <label>Projects and Resources</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Projects and Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects and Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects_and_Resources__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Resource</description>
    <inlineHelpText>Resource</inlineHelpText>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Projects and Resources</relationshipLabel>
    <relationshipName>Projects_and_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projects_and_Resources__c/fields/Resource_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Resource_End_Date__c</fullName>
    <description>End date</description>
    <inlineHelpText>End date</inlineHelpText>
    <label>Resource End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Projects_and_Resources__c/fields/Resource_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Resource_Start_Date__c</fullName>
    <description>Start date</description>
    <inlineHelpText>Start Date</inlineHelpText>
    <label>Resource Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Resource Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <inlineHelpText>First Name</inlineHelpText>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <inlineHelpText>Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resources_Expertise__c/Resources_Expertise__c.object-meta.xml
<CustomObject>
    <description>Resources and expertise</description>
    <label>Resources and Expertise</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Resources Exp Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources and Expertise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resources_Expertise__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Certified or not</description>
    <inlineHelpText>Certified?</inlineHelpText>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resources_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Expertise</description>
    <inlineHelpText>Expertise</inlineHelpText>
    <label>Expertise</label>
    <referenceTo>Expertise__c</referenceTo>
    <relationshipLabel>Resources and Expertise</relationshipLabel>
    <relationshipName>Resources_and_Expertise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resources_Expertise__c/fields/Expertise_Level__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Level__c</fullName>
    <description>Expertise level</description>
    <inlineHelpText>Expertise level</inlineHelpText>
    <label>Expertise Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resources_Expertise__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Resource</description>
    <inlineHelpText>Resource</inlineHelpText>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resources and Expertise</relationshipLabel>
    <relationshipName>Resources_and_Expertise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddSampleEAData.cls
public class AddSampleEAData {

public pagereference generate() {
try{
 SampleData__c obj = SampleData__c.getInstance('SampleApp');
 
if(obj.Populated__c == 'false'){

StaticResource defaultProject = [Select  s.Body From StaticResource s where s.Name LIKE 'SampleProject%'];
        blob Data = defaultProject.Body;
        String contentFile = Data.toString();
        String[] filelines = contentFile.split('\n');
        List<Projects__c> defaultsp = new List<Projects__c>();
        for (Integer i=1;i<filelines.size();i++)
        {
            Projects__c p = new Projects__c();
            String[] inputvalues = filelines[i].split(',');
            p.Name = inputValues[0];
            p.Start_Date__c = date.valueof(inputValues[1]);
            p.End_Date__c = date.valueof(inputValues[2]);
            p.Status__c = inputValues[3];
            p.Category__c = inputValues[4];
            p.Country__c = inputValues[5];
            p.sample__c = Boolean.Valueof(inputValues[6]);
            defaultsp.add(p);    
        }
        insert defaultsp;
        }
        
      }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
      
       return null;
    }
        

     
     
  public pagereference DeleteRecords(){  
 SampleData__c obj = SampleData__c.getInstance('SampleApp');
   
      try{
      
         list<projects__c> proj = [select id from projects__c];
         delete proj;
         list<resource__c> resource = [select id from resource__c];
         delete resource;
         List<Expertise__c> expertise = [select id from expertise__c];
         delete expertise;
         
       obj.Populated__c = 'false';
       update obj;
        
         
         }
         catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
         
        return null;
     }
     
 public pagereference generateResource() {  
 try{    
 StaticResource defaultResource = [Select  s.Body From StaticResource s where s.Name LIKE 'SampleResource%'];
        blob ResourceData = defaultResource.Body;
        String contentFile2 = ResourceData.toString();
        String[] filelines2 = contentFile2.split('\n');
        List<Resource__c> defaultsr = new List<Resource__c>();
        for (Integer i=1;i<filelines2.size();i++)
        {
            Resource__c r = new Resource__c();
            String[] inputvalues = filelines2[i].split(',');
            r.First_Name__c = inputValues[0];
            r.Last_Name__c = inputValues[1];
            r.Years_of_Experience__c = integer.valueof(inputValues[3]);
            r.sample__c = boolean.valueOf(inputValues[4]);
            defaultsr.add(r);    
        }
        insert defaultsr;
        }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
      
    return null;
   
   }
   
   public pagereference generateExpertise() { 
    try{
        StaticResource defaultskills = [Select  s.Body From StaticResource s where s.Name LIKE 'SampleExpertise%'];
        blob SkillsData = defaultskills.Body;
        String contentFile3 = SkillsData.toString();
        String[] filelines3 = contentFile3.split('\n');
        List<Expertise__c> defaultssk = new List<Expertise__c>();
        for (Integer i=1;i<filelines3.size();i++)
        {
            Expertise__c s = new Expertise__c();
            String[] inputvalues = filelines3[i].split(',');
            s.Name = inputValues[0];
            s.Type__c = inputValues[1];
            s.Certification_Required__c = boolean.valueof(inputValues[2]);
            s.HOT_TECHNOLOGY__C = boolean.valueof(inputValues[3]);
            defaultssk.add(s);    
        }
        insert defaultssk;
         }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
        return null;
        }
        
   public pagereference generateProjectExpertise() { 
    try{
        StaticResource defaultskills = [Select  s.Body From StaticResource s where s.Name LIKE 'SampleProjExpertise%'];
        blob SkillsData = defaultskills.Body;
        String contentFile3 = SkillsData.toString();
        String[] filelines3 = contentFile3.split('\n');
        List<Projects_and_Expertise__c> defaultssk = new List<Projects_and_Expertise__c>();
        for (Integer i=1;i<filelines3.size();i++)
        {
            Projects_and_Expertise__c s = new Projects_and_Expertise__c();
            String[] inputvalues = filelines3[i].split(',');
            s.EXPERTISE_LEVEL__C = decimal.valueof(inputValues[0]);
            s.NUMBERREQUIRED__C = decimal.valueof(inputValues[1]);
            s.Project_Name_Sample__c = inputValues[2];
            s.Expertise_Name_Sample__c = inputValues[3];
            s.sample__c = boolean.valueof(inputValues[4]);
            
            defaultssk.add(s);    
        }
        insert defaultssk;
         }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
        return null;
        }
     public pagereference generateResourceExpertise() { 
    try{
        StaticResource defaultskills = [Select  s.Body From StaticResource s where s.Name LIKE 'SampleResExpertise%'];
        blob SkillsData = defaultskills.Body;
        String contentFile3 = SkillsData.toString();
        String[] filelines3 = contentFile3.split('\n');
        List<Resources_Expertise__c> defaultssk = new List<Resources_Expertise__c>();
        for (Integer i=1;i<filelines3.size();i++)
        {
            Resources_Expertise__c s = new Resources_Expertise__c();
            String[] inputvalues = filelines3[i].split(',');
            s.CERTIFIED__C = boolean.valueof(inputValues[0]);
            s.EXPERTISE_LEVEL__C = integer.valueof(inputValues[1]);
            s.Resource_Name_Sample__c = inputValues[2];
            s.Expertise_Name_Sample__c = inputValues[3];
            s.sample__c = boolean.valueof(inputValues[4]);
            
            defaultssk.add(s);    
        }
        insert defaultssk;
         }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
        return null;
        }
      
      public pagereference generatePRE() { 
    try{
        StaticResource defaultskills = [Select  s.Body From StaticResource s where s.Name LIKE 'SamplePRE%'];
        blob SkillsData = defaultskills.Body;
        String contentFile3 = SkillsData.toString();
        String[] filelines3 = contentFile3.split('\n');
        List<Projects_and_Resources__c> defaultssk = new List<Projects_and_Resources__c>();
        for (Integer i=1;i<filelines3.size();i++)
        {
            Projects_and_Resources__c s = new Projects_and_Resources__c();
            String[] inputvalues = filelines3[i].split(',');
            s.RESOURCE_START_DATE__C = date.valueof(inputValues[0]);
            s.RESOURCE_END_DATE__C = date.valueof(inputValues[1]);
            s.Resource_Name_Sample__c = inputValues[3];
            s.Expertise_Name_Sample__c = inputValues[4];
            s.PROJECT_NAME_SAMPLE__C = inputValues[2];
            s.sample__c = boolean.valueof(inputValues[5]);
            
            defaultssk.add(s);    
        }
        insert defaultssk;
         }catch(exception e){
      
      system.debug('Data Insert Error'+ e.getMessage());
      
      }
        return null;
        }
     
        
        
     
     public pagereference generateAll() {
     generate();
     generateResource();
     generateExpertise();
     generateProjectExpertise();
     generateResourceExpertise();
     generatePRE();
     
     return null;
     
     }   

}